apiVersion: v1
kind: Service
metadata:
  name: ecm516-observacoes-service
spec:
  type: NodePort
  selector:
    app: observacoes
  ports:
    - name: observacoes
      protocol: TCP
      port: 5100
      targetPort: 5100