apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ecm516-observacoes-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: observacoes
  template:
    metadata:
      labels: 
        app: observacoes
    spec:
      containers:
        - name: observacoes
          image: m3ngal/ecm516-observacoes
          resources:
            limits:
              memory: 256Mi
              cpu: 1
            requests:
              memory: 256Mi
              cpu: 1